---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hc-volume-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hcloud-volumes
---
kind: Pod
apiVersion: v1
metadata:
  name: fio-hcloud
spec:
  volumes:
    - name: hc-volume
      persistentVolumeClaim:
       claimName: hc-volume-claim
  containers:
    - name: fio
      image: alpine
      command: ['sh', '-c', 'apk add fio && sleep 100000']
      volumeMounts:
        - mountPath: "/volume"
          name: hc-volume

